source $HOME/AppData/Local/nvim/vim-plug/puglins-config/markdown-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/lspconfig.rc.vim
"source $HOME/AppData/Local/nvim/vim-plug/puglins-config/flutter-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/prettier-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/dashboard-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/floaterm-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/nvim-tree-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/closetag-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/lightline-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/vim-go-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/quickscope-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/barbar-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/signify-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/telescope-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/wildmenu-config.vim
