source $HOME/AppData/Local/nvim/vim-plug/puglins-config/markdown-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/coc-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/prettier-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/startify-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/floaterm-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/nerdtree-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/closetag-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/lightline-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/vim-go-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/quickscope-config.vim
source $HOME/AppData/Local/nvim/vim-plug/puglins-config/barbar-config.vim
